name: Build Chrome Extension

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'packages/chrome/**'
      - '.github/workflows/build-chrome-extension.yml'

permissions:
  contents: write
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'
      
      - name: Install dependencies
        run: yarn install
        
      - name: Build Chrome extension
        run: |
          cd packages/chrome
          yarn build:ship
          
      - name: Rename and move zip file
        run: |
          mkdir -p artifacts
          cp packages/chrome/build/chrome-mv3-prod.zip artifacts/mockey-patcher.zip
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: chrome-extension
          path: artifacts/mockey-patcher.zip 